<?php
/* 
Song class- adds, deletes, prints songs
*/
class Song {
	// This class is used to create and maintain songs for the survey
		
	private $songID; //song ID is AUTO_INCREMENT in the database-generated by the db
	private $artist;
	private $title;
	private $votes;

	//This is the constructor 
	public function __construct($artist, $title) {
		$this->artist = $artist;
		$this->title = $title;
		$this->votes = 0;
	}
	
	//set function
	public function __set($name, $value){
		$this->$name = $value;
	}	
	
	//get function: just returns the value of the desired variable
	public function __get($name){
		return $this->$name;
	}
	
	public function addSong($db){	
		//This adds a song object to the song table
		//Song_ID is auto_increment, and Votes has a default of 0 
		$Artist = $this->artist;
		$Title = $this->title;
		$query = "INSERT INTO songs12 (Artist,Title) VALUES ('$Artist','$Title')";
        $result = $db->query($query);
		if (!$result || $db->affected_rows == 0){
			echo "<h2>ERROR executing query *$query*. Error message: ". $db->errno ." ". $db->error ."</h2>";
			return false;
		}
		else{
			return true;
		}
    }	

	public static function printSongs($db){
		//create a table with all songs
		//create the query
		$query = "SELECT SongID, Artist, Title, Votes FROM songs12 ORDER BY Artist,Title"; 
		//send the query to the database
		$result = $db->query($query);
		//check that everything OK
		if (!$result){
			return false;
		}
		//process the results and construct the table
	    $num_results = $result->num_rows;
	    $table = '';
		if ($num_results > 0){
		
		   $table = $table . 
		   '<table border = "2">
  		   <tr><th width="150">Artist</th><th width="150">Title</th></tr>';
		
		   for ($i=0; $i<$num_results; $i++)	//loop through all songs
		   {
              $row = $result->fetch_assoc(); //retrieves a row from the result
              $table = $table 
				.'<tr>'
				. '<td>'. $row['Artist'] . '</td>'
				. '<td>'. $row['Title'] . '</td>'
				 .'<td><input type="radio" name = "songID"'
				. ' value="'. $row['SongID']. '" /></td>'
				.'</tr>';
		   }
			$table = $table . '</table><br/><br/>';
		}	
		$result->free(); //de-allocate the memory for the results
		
        return $table;
	}

	//add a song to cart
	public static function addToCart($songID){
		//just increase the quantity by 1 if song in cart already
		//set quantity to one if song not already in cart
		if(isset($_SESSION['shoppingCart'][$songID]) ){
			$_SESSION['shoppingCart'][$songID]++;
		}
		else{
			$_SESSION['shoppingCart'][$songID] = 1;
		}
			
		return true;
		
		
	}
	
	//view the cart
	public static function viewCart(){
		//loop through each song and add the song id and quantity to the resulot string
		//return the resulting string
		$result = '<h2>Shopping cart content: </h2>';
		foreach($_SESSION['shoppingCart'] as $songID => $quantity){
			$result .= "<p>SongID: $songID quantity: $quantity</p>";
		}
		return $result;
	
	}
	

	
	
}
?>